### ISSUE TITLE
[Bug]: Crash when ungrouping elements

### ISSUE THREAD

**Issue by peilingjiang** [tldraw/tldraw#4126] opened 2024-07-09 22:08 UTC
### What happened?

https://github.com/tldraw/tldraw/assets/25191575/b15383bf-d8c6-4d2e-aee1-309387fbd585

When I tried to ungroup elements that are connected with each other and some others outside of the group, the canvas crashed. Here's the detail:

```
Error: b16l >= b16l
    at Al (https://www.tldraw.com/assets/index-RwMyKwLM.js:105:5033)
    at Zi (https://www.tldraw.com/assets/index-RwMyKwLM.js:105:5769)
    at Kc (https://www.tldraw.com/assets/index-RwMyKwLM.js:105:5876)
    at ne.reparentShapes (https://www.tldraw.com/assets/index-RwMyKwLM.js:138:61668)
    at https://www.tldraw.com/assets/index-RwMyKwLM.js:138:82954
    at https://www.tldraw.com/assets/index-RwMyKwLM.js:134:38408
    at tq (https://www.tldraw.com/assets/index-RwMyKwLM.js:105:17740)
    at Bi (https://www.tldraw.com/assets/index-RwMyKwLM.js:105:17919)
    at ete.batch (https://www.tldraw.com/assets/index-RwMyKwLM.js:134:38400)
    at ne.batch (https://www.tldraw.com/assets/index-RwMyKwLM.js:138:27357)
    at ne.ungroupShapes (https://www.tldraw.com/assets/index-RwMyKwLM.js:138:82804)
    at onSelect (https://www.tldraw.com/assets/index-RwMyKwLM.js:329:7864)
    at onSelect (https://www.tldraw.com/assets/index-RwMyKwLM.js:329:80027)
    at d.addEventListener.once (https://www.tldraw.com/assets/index-RwMyKwLM.js:329:63757)
    at HTMLDivElement.r (https://www.tldraw.com/assets/index-RwMyKwLM.js:89:1426)
    at https://www.tldraw.com/assets/index-RwMyKwLM.js:206:10045
    at Ya (https://www.tldraw.com/assets/index-RwMyKwLM.js:43:37117)
    at Dr.flushSync (https://www.tldraw.com/assets/index-RwMyKwLM.js:43:56292)
    at r_ (https://www.tldraw.com/assets/index-RwMyKwLM.js:206:10029)
    at u (https://www.tldraw.com/assets/index-RwMyKwLM.js:329:63773)
    at https://www.tldraw.com/assets/index-RwMyKwLM.js:206:6725
    at Object.sN (https://www.tldraw.com/assets/index-RwMyKwLM.js:40:9855)
    at aN (https://www.tldraw.com/assets/index-RwMyKwLM.js:40:10009)
    at lN (https://www.tldraw.com/assets/index-RwMyKwLM.js:40:10066)
    at vE (https://www.tldraw.com/assets/index-RwMyKwLM.js:40:31446)
    at R2 (https://www.tldraw.com/assets/index-RwMyKwLM.js:40:31863)
    at https://www.tldraw.com/assets/index-RwMyKwLM.js:40:36776
    at vb (https://www.tldraw.com/assets/index-RwMyKwLM.js:43:36935)
    at s2 (https://www.tldraw.com/assets/index-RwMyKwLM.js:40:8991)
    at Iv (https://www.tldraw.com/assets/index-RwMyKwLM.js:40:33150)
    at Vx (https://www.tldraw.com/assets/index-RwMyKwLM.js:40:17360)
    at EN (https://www.tldraw.com/assets/index-RwMyKwLM.js:40:17144)
    at HTMLDivElement.r (https://www.tldraw.com/assets/index-RwMyKwLM.js:89:1426)
```

### How can we reproduce the bug?

I failed to reproduce it by creating the same schema on another page or copy-pasting the shapes into another browser.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment] 2024-07-10 08:20
Hey! Did this happen in a multiplayer room? Were other people present in it?

**Comment by peilingjiang** [comment] 2024-07-10 15:59
No, it was a personal file.

**Comment by MitjaBezensek** [comment] 2024-07-11 06:44
> No, it was a personal file.

I see, thanks for letting us know.

**Comment by mimecuvalo** [comment] 2024-07-24 12:35
duplicate of https://github.com/tldraw/tldraw/issues/3932

**Closed by mimecuvalo** 2024-07-24 12:35 UTC
Labels: bug
