### ISSUE TITLE
[bug] Undo doesnt work when the detail popup window is open

### ISSUE THREAD

**Issue by scottyantipa** [tldraw/tldraw#411] opened 2021-11-29 04:46 UTC
To reproduce:
- Put some shapes on the canvas and select them
- Open the detail menu (the one labeled '...')
- Click any action in there, like align the shapes etc
- Do 'undo' using the keyboard shortcut (cmd/ctrl z)
- Note that the action does NOT undo. Undo does work if triggered via Hamburger -> Edit -> Undo

Found on: https://www.tldraw.com/

Example:

https://user-images.githubusercontent.com/3643611/143810341-8c62d9e1-2f6f-4bad-b646-a8ace8ca320e.mov

**Comment by megnakokkalera** [comment] 2021-12-01 00:17
Hi! I am interested in fixing this bug. If nobody else is already working on it, could you assign this issue to me @steveruizok? Thanks!

**Comment by proful** [comment] 2021-12-01 00:26
@megnakokkalera please raise a PR

**Comment by megnakokkalera** [comment] 2021-12-01 01:41
> @megnakokkalera please raise a PR

Will create a PR after I am finished with the changes. Just wanted to claim this issue first before working on it. Thanks!

**Comment by steveruizok** [comment] 2021-12-01 14:24
Let me know how you get on @megnakokkalera. 👍 We need to be careful about allowing keyboard events to leave the menus, as menus as navigable via the keyboard, and may include textfields or other places where keyboard events shouldn't effect the rest of the app.

**Comment by megnakokkalera** [comment] 2021-12-03 03:11
> Let me know how you get on @megnakokkalera. 👍 We need to be careful about allowing keyboard events to leave the menus, as menus as navigable via the keyboard, and may include textfields or other places where keyboard events shouldn't effect the rest of the app.

Do you mind elaborating on this? Thanks so much!

**Comment by megnakokkalera** [comment] 2021-12-03 05:23
@steveruizok Is there a significance to canHandleEvent and elm in KeyboardShortcuts? If the function canHandleEvent returns true always, you can hit ctrl-z when the menu is open and it will work. The problem is that when you open a menu, the active element becomes the menu but elm does not include the menu. So, the function returns false and you are unable to do ctrl-z when the menu is open. The fix to me would be to include the menu in elm or to include a special case inside canHandleEvent that returns true if the menu is open and the active element is the menu. Let me know your thoughts 👍

**Comment by megnakokkalera** [comment] 2021-12-05 20:51
attached is video of the fix
it would be great if you could review, thanks!

https://user-images.githubusercontent.com/89897185/144763414-71c01b73-8e51-418b-8572-0a6551b46eab.mov

**Closed** 2021-12-06 18:23 UTC
Labels: bug
