### ISSUE TITLE
Configure tool initial styles

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#2701] opened 2024-02-01 08:13 UTC
> Hey, I try to set the default font style to `sans` on editor mount but whenever I create a rectangle, the font style goes back to the original `draw` style. It would be great if I could specify the initial styles via props.

**Comment by steveruizok** [comment] 2024-03-02 18:52
I think this is how the Styles API works with defaults. We'd have to be setting stylesForNextShape.

**Comment by mimecuvalo** [comment] 2024-07-23 15:02
duplicate of https://github.com/tldraw/tldraw/issues/2377

**Closed by mimecuvalo** 2024-07-23 15:02 UTC
Labels: feature
