### ISSUE TITLE
[Bug]: Right clicking on a selected group changes the selection from the group to the element under the cursor

### ISSUE THREAD

**Issue by rjt-rockx** [tldraw/tldraw#3936] opened 2024-06-13 19:47 UTC
### What happened?

When trying to access context menu options for a group of elements, I select the entire group and then try to right click on it. 
But, since right clicking on a selected group changes the selection to whatever element within the group is under the cursor, I cannot select the group itself to access context menu options (like copy as png), only the individual elements underneath it. 
As a result, those actions only run on the individual element and not the group itself. 

### How can we reproduce the bug?

https://github.com/tldraw/tldraw/assets/10488070/3bef03b5-8021-41a0-b963-641374240231

Chrome 126, Windows 11 23H2

### What browsers are you seeing the problem on?

Chrome

### Contact Details

rjt.rockx@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment] 2024-07-24 12:54
duplicate of https://github.com/tldraw/tldraw/issues/3421 and it seems like it's fixed now 👍

**Closed by mimecuvalo** 2024-07-24 12:54 UTC
Labels: bug
