### ISSUE TITLE
Ctrl + S Not Working

### ISSUE THREAD

**Issue by chipallen2** [tldraw/tldraw#1239] opened 2023-04-04 21:29 UTC
If I open an existing file > then change something > then hit ctrl + s it does not save my file. It tries to save as and make a new file.

- File > Open File
- Change something
- Ctrl + S on keyboard

It tries to save a new tldraw file. Old site used to just save to my existing file on my computer.

![image](https://user-images.githubusercontent.com/4950543/229926965-9f820531-28fd-4c72-b5cd-efd2b8d87366.png)

![image](https://user-images.githubusercontent.com/4950543/229926940-93e9c678-2674-4605-a154-c51363caf778.png)

**Comment by steveruizok** [comment] 2023-05-08 14:57
This should now keep the same filename, so you can over-write a previous saved file. By the way, if you work a lot with saved files, you might prefer to use our [Visual Studio Code extension](https://marketplace.visualstudio.com/items?itemName=tldraw-org.tldraw-vscode).

**Comment by steveruizok** [comment] 2023-05-10 11:50
Closing this one as the feature is working as intended (though perhaps not as expected!).

**Closed by steveruizok** 2023-05-10 11:50 UTC
