### ISSUE TITLE
Better error handling when uploading images

### ISSUE THREAD

**Issue by Taha-Hassan-Git** [tldraw/tldraw#2344] opened 2023-12-19 11:11 UTC
When uploading an image, a failed upload can lead to a validation error. Our validation errors cause the app to crash. We should implement better error handling around this part of the app so that a failed upload does not crash the app.

**Comment by HARSH048** [comment] 2024-01-12 19:23
Hi @Taha-Hassan-Git  ,
I'm Harsh, interested in contributing tldraw. I've been exploring the project and am particularly interested on this issue. I'd love to contribute by working on this issue.
Looking forward to contributing to this issue Can you assign this to me. and tell me in which file the issue is present?

**Comment by mimecuvalo** [comment] 2024-07-23 14:26
Looks like this is better now, but lemme know if you're still seeing an issue @Taha-Hassan-Git !

**Closed by mimecuvalo** 2024-07-23 14:26 UTC
