### ISSUE TITLE
[Feature]: Zoom with just mouse

### ISSUE THREAD

**Issue by e1turin** [tldraw/tldraw#3287] opened 2024-03-27 20:28 UTC
### What's the feature?

It's really convenient to zoom canvas with just mouse. Usually applications zoom with Ctrl+scroll but more convenient way is hold left mouse button and scroll.

Such control has Pixso white board.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment] 2024-07-23 15:27
dupe of https://github.com/tldraw/tldraw/issues/1344

**Closed by mimecuvalo** 2024-07-23 15:27 UTC
Labels: enhancement
