### ISSUE TITLE
Deleted image asset remains in store

### ISSUE THREAD

**Issue by wulart** [tldraw/tldraw#2711] opened 2024-02-03 06:41 UTC
### What happened?

Upload a picture or video and then delete it. Use the function store.getSnapshot() or store.serialize(), and the asset of the image is still in the store.
![image](https://github.com/tldraw/tldraw/assets/8372032/fd7a9804-aec2-4eb3-b998-7958b891d80d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment] 2024-07-22 14:36
This one is a bit tricky. We cannot just delete the asset since the user might undo the image deletion in which case the asset might be gone. We also reuse assets if you, for example, duplicate a shape. So we'd need to put some strategies in place on when is it safe to delete assets.

**Comment by mimecuvalo** [comment] 2024-07-23 10:01
Going to reopen. I think it's worth thinking about this, especially for localStorage management, disk space and the like.

**Comment by mimecuvalo** [comment] 2024-07-23 13:45
actually, dupe of https://github.com/tldraw/tldraw/issues/2257

**Closed by mimecuvalo** 2024-07-23 13:45 UTC
