### ISSUE TITLE
Cannot undo after page reload

### ISSUE THREAD

**Issue by jackson-dahl42** [tldraw/tldraw#3784] opened 2024-05-20 20:34 UTC
### What happened?

When you draw something you are normally able to press the undo button, but when you draw something then reload the page you are no longer able to undo what you did previously before you reloaded the page. I expected the web app to still be able to undo what I have drawn after reloading.
Before reloading page:
![Screenshot 2024-05-20 163057](https://github.com/tldraw/tldraw/assets/99228002/ab19a0e7-c4f4-43cf-b5d5-64bae5e9da44)
After reloading page (the undo button is gone):
![Screenshot 2024-05-20 163157](https://github.com/tldraw/tldraw/assets/99228002/0bcf75cb-bd8f-42d3-a1e9-99759dc49943)

### How can we reproduce the bug?

Draw something then reload the page. You will not be able to undo what you have done before reloading the page.

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Contact Details

jdahl087@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ds300** [comment] 2024-05-21 09:17
Hi! Thanks for the report!

This is not a bug, it's expected behavior (for now). The logistics of preserving undo/redo state across browser sessions is kinda sprawling, we're unlikely to tackle it any time soon unless a big customer asks for it.

I'm gonna close this issue but thanks again for raising it.

**Closed by ds300** 2024-05-21 09:17 UTC
