### ISSUE TITLE
[bug] Too many cursor show up in Multiplayer mode.

### ISSUE THREAD

**Issue by lichin-lin** [tldraw/tldraw#578] opened 2022-02-15 16:40 UTC
First of all, thanks for making the multiplayer feature, it works in most cases!

Here is one bug I found: If you try to refresh a tab **with an element selected**, somehow the `removeuser` function in `useMultiplayerState.ts` will not be triggered, so in other user's views, they will see more and more cursors show up (but actually, they all indicate the same user.)

I am not sure if this has to do with how Liveblock sends the event to a room, or, we didn't really clean up the userID in our storage so that we can't show the correct amount of cursor in a room 🙌

https://user-images.githubusercontent.com/10290616/154104177-8a26a71b-d30f-48c0-bd48-afdd73ed907f.mov

**Comment by a-type** [comment] 2022-03-30 20:30
If you're using Liveblocks I'd recommend this improvement we made in our app vs the example code for tracking active users:

```
liveBlocks.subscribe('others', (others, event) => {
  if (event.type === 'leave') {
    if (event.user.presence) {
      app.removeUser(event.user.presence.id);
    }
  } else {
    app.updateUsers(
      others.map((p) => p.presence)
    );
  }
})
```

Assuming you're storing TLDraw user data directly in Liveblocks presence, `presence.id` will be the TLDraw user ID.

By listening explicitly for Liveblocks user leave events, which are delivered reliably, you can drop the `beforeunload` handlers and the use of broadcast events to tell peers you're leaving.

**Comment by judicaelandria** [comment] 2022-05-23 16:12
Hi @lichin-lin , this seems to be fixed, could you test it again please, if it's working for you, please close the issue! thanks

**Comment by lichin-lin** [comment] 2022-05-23 16:19
I think this issue still occurs, and it's quite easily to reproduce:

1. open a multiplayer room
2. open two tabs
3. keep refreshing on one of the tab
4. you will get the following result on the other tab (where too many cursor stay on the page)

https://user-images.githubusercontent.com/10290616/169863224-d7b6c9ee-ac7e-4eb7-bdb7-9765cca85600.mov

**Comment by judicaelandria** [comment] 2022-05-23 16:22
It appears because you're on the same browser, I tried it on a different browser

**Comment by judicaelandria** [comment] 2022-05-23 16:54
okay, I can reproduce it now! I'll try to fix it

**Comment by judicaelandria** [comment] 2022-05-23 17:26
the problem was the user presence was never deleted when they exit or leave so that's why there are many cursor because the user presence before he leaves is never deleted

**Comment by judicaelandria** [comment] 2022-05-24 03:20
@lichin-lin can you try with this link if it's working, please? [link preview tldraw](https://tldraw-git-fork-judicaelandria-fix-user-presence-41cebb-tldraw.vercel.app/)

**Comment by lichin-lin** [comment] 2022-05-24 03:26
yes!! it's working perfectly!

**Comment by judicaelandria** [comment] 2022-05-25 13:26
okay it's merged, can you close this issue now @lichin-lin  please ? thanks

**Closed** 2022-07-24 22:50 UTC
Labels: bug
