### ISSUE TITLE
[Bug]: Poor/slow editing experience after a moderate amount of notes added to slide

### ISSUE THREAD

**Issue by jamievicary** [tldraw/tldraw#2274] opened 2023-11-30 13:52 UTC
### What happened?

We are using tldraw in my research group to take notes during research meetings. It is an excellent and fully-featured program, thanks to the community who have done such an excellent job putting it together. However we have noticed that once we have been writing on a page for 10 minutes or so, the performance really starts to drop off. We are just writing using the pen tool, not using shapes. It seems that the app becomes unable to capture stylus positions with a sufficiently high frequency, so we have to start writing very slowly. The browser tab memory does not seem to be becoming excessive so I'm not sure what would cause this. Opening a new page solves the problem and writing becomes snappy once again.

It could be that this is a fundamental limitation with the tool. However I don't see how the existence of objects elsewhere on the page should reduce the point capture frequency for new pen marks.

### How can we reproduce the bug?

Use the pen tool to write for 5 or 10 minutes on a single page.

### What browsers are you seeing the problem on?

Chrome

### Contact Details

jamievicary@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment] 2023-12-01 08:20
The number of elements on the screen can definitely cause slowdowns. Pen shapes have a lot of points to make them look good, which can start weighing down the browser.

Is there any chance you could send us an example of such a document so that we could investigate? You can go to the menu, File, Save a copy (or press `Cmd / Ctrl + s`). Can share an email or you can reach out to me on discord.

**Comment by calebeby** [comment] 2023-12-05 21:14
I have noticed a similar issue in the past. This document is not particularly large and the problem is not too terrible compared to larger documents I've made in the past (with more handwriting), but it still is noticeably slower to write in it compared to an empty document. I have to write slowly for it to keep up and a lot of the strokes look really bad.

https://www.tldraw.com/r/aeO5aF6JF2V9MNJS371XY?viewport=1516,2895,2712,1541&page=page:OS7K6JByaiADITjPQu0bO

**Comment by MitjaBezensek** [comment] 2023-12-06 07:54
Thanks for sharing this! Can you also let us know what kind of a device and browser are you using?

**Comment by calebeby** [comment] 2023-12-09 20:41
I've noticed this in Chrome edge and Firefox on a ThinkPad X1 Carbon with a huion graphics tablet as well as on my phone Galaxy s21 ultra

**Comment by KySpace** [comment] 2024-04-07 11:28
Same here. This problem has been there since the last major version. Sometimes closing the tab and opening makes it a bit better, and sometimes pen curves just become lines. 

I am using a Wacom tablet on Edge. I really hope that the team can have more tests with heavy duty pages. The infinite canvas is infinite for a reason, after all.

**Comment by jamievicary** [comment] 2024-04-08 09:07
I wonder if there is an update from the dev team on this. Your whiteboard app is the only good one out there -- and this is the only limitation that's preventing massive use from our research group.

**Comment by ysulyma** [comment] 2024-04-09 20:37
I'm having the same issue---tried using it during a meeting, and kept having to start new pages. I was hoping to use tldraw for recording lectures, but this won't be possible with the performance issues.

**Comment by MitjaBezensek** [comment] 2024-04-12 19:15
Hey! We did a bunch of updates on performance and we just shipped this this week (2 days ago). Is it any better for you now? We improved a bunch of things, but we still have a few more improvements planned.

@KySpace I noticed that you are using the grid. Try turning it off and see if that solves it? We are aware that grid can get slow and have some ideas on how we could improve that.

**Comment by KySpace** [comment] 2024-04-16 00:12
@MitjaBezensek Yeah. I can say that it has improved. I'll keep trying with larger files.

**Comment by MitjaBezensek** [comment] 2024-07-22 14:12
We now also added an option to flatten the shapes. This turns multiple shapes into one image, which helps with performance a lot. These are no longer editable, so there are definitely drawbacks to this, but it should help with large documents.
![image](https://github.com/user-attachments/assets/3b32c899-691b-484a-9e83-f5bd262ef129)

**Comment by mimecuvalo** [comment] 2024-07-23 13:44
Yeah, indeed after our work in April on performance this should be greatly improved! If there's more performance issues of this nature, I'd ask please to create a new bug on Github (with an example) so that we can figure out any new specific problems as they arise.

**Closed by mimecuvalo** 2024-07-23 13:44 UTC
Labels: bug
