### ISSUE TITLE
[Example Request]: Make canvas as finite one. 

### ISSUE THREAD

**Issue by Kesavaraja** [tldraw/tldraw#3727] opened 2024-05-09 06:48 UTC
### What's the example?

Thanks for the wonderful package. 
I know that biggest advantage of Tldraw is Infinite canvas but is it possible to make it finite for the zoom level. I mean the shapes should not be moved out of view. 
I saw an example which shows the shapes cannot be moved more than the radius but I need example for rectangle/square one. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment] 2024-07-24 10:59
Duplicate of https://github.com/tldraw/tldraw/issues/1946

Example is https://examples.tldraw.com/camera-options
(although it's currently busted today and a fix is coming soon)

**Closed by mimecuvalo** 2024-07-24 10:59 UTC
Labels: Example Request
