### ISSUE TITLE
VS Code extension: embed tldraw data in PNG

### ISSUE THREAD

**Issue by wrthwhl** [tldraw/tldraw#3325] opened 2024-04-02 14:03 UTC
Love tldraw and really appreciate the work you are doing!

### What's the feature?

It would be fantastic if the tldraw vs code extension could embed the source data of a drawing in a png (and/or svg) file. This would enable the extension to recognize files with e.g. a `tldraw.png` extension and in e.g. github the file would be shown as an image.

The vscode extensions for excalidraw and draw.io are doing this already.

<img width="740" alt="image" src="https://github.com/tldraw/tldraw/assets/6626615/25736303-4580-43b9-8cc5-7d4c1585ddfd">

_From https://marketplace.visualstudio.com/items?itemName=pomdtr.excalidraw-editor#edit-images_

### Contact Details

Feeling a bit anxious to leave my email address here. Is it really required?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment] 2024-07-23 14:53
Duplicate of https://github.com/tldraw/tldraw/issues/1666
Closing this issue in favor of that one (that isn't vscode specific)

**Closed by mimecuvalo** 2024-07-23 14:53 UTC
