### ISSUE TITLE
Text issue in canvas

### ISSUE THREAD

**Issue by spiritwarri0r** [tldraw/tldraw#2882] opened 2024-02-20 13:56 UTC
### What happened?

It happened recently, this didn't happen before, maybe is because of the last update. 
When I try to create new text it automatically create a predefined canvas that I can't modify,  

I attach this video example:
1. From 00:03 to 00:06  (Here when I click with the cursor the line where the text start should be on the point of the cursor.
2. From 00:06 to 00:18 (I'm just write continuously random characters, I never pressed enter. Then when I finished I just click outside
3. From 00:52 to 01:02 (Here I write few characters then press enter, then I write again few then press enter, trying to create a list. As you can see the text disappear from the view, but when I outside the canvas then appear all the text.

[tldrawtextissue.webm](https://github.com/tldraw/tldraw/assets/7793295/36208eba-1bf3-44e3-9131-52be17b9b902)

### What browsers are you seeing the problem on?

Firefox

### Contact Details

spirit_warrior@rocketmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomeHats** [comment] 2024-02-20 17:47
Thanks for the report! I think this is a duplicate of #2854 and is fixed on staging.tldraw.com - we should be deploying a fix within the next couple of days. Feel free to re-open if you think this is a separate issue!

**Closed by SomeHats** 2024-02-20 17:47 UTC
