### ISSUE TITLE
[Feature]: Dockerising the application to runs container

### ISSUE THREAD

**Issue by jinnabaalu** [tldraw/tldraw#1881] opened 2023-09-16 06:04 UTC
### What's the feature?

Dockerising the applications, helps to run the application as container

### Contact Details

jinna.balu@outlook.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment] 2024-07-22 14:07
Duplicate of #1741

**Closed by MitjaBezensek** 2024-07-22 14:07 UTC
Labels: enhancement
