### ISSUE TITLE
[Feature]: How can I get the preloading status of assets?

### ISSUE THREAD

**Issue by tuntun0609** [tldraw/tldraw#1862] opened 2023-09-11 12:22 UTC
### What's the feature?

I would like to inquire about how to determine when assets resource loading is complete. I've looked through the documentation (including both the alpha and canary versions), as well as the source code, but there doesn't seem to be an event or method that notifies me when the assets have finished loading (perhaps I just haven't seen it).
Lastly, thank you for maintaining tldraw :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sanyam-jain30** [comment] 2023-09-16 17:11
If the issue is still open. Can I be assigned to this issue? I have some expertise in Open Source Contribution.

**Comment by mimecuvalo** [comment] 2024-07-22 15:05
Hello! You should be able to listen to the `onMount` callback. This happens after preloading has been done.
Example docs: https://tldraw.dev/reference/editor/TLOnMountHandler

**Closed by mimecuvalo** 2024-07-22 15:05 UTC
Labels: enhancement
