### ISSUE TITLE
Add Korean typography support

### ISSUE THREAD

**Issue by Na-hyunwoo** [tldraw/tldraw#3146] opened 2024-03-13 17:08 UTC
### What's the feature?

Hello, I am a developer who is looking at your work with interest. 
I like to use tldraw's canvas when working for desing docs. 
The fact that the system font is applied to the Korean font greatly reduces the feel of the canvas. 
Are there any plans to apply Korean fonts? 
Or is there anything I can do regarding the above task?

The Shantell Sans you're using doesn't have Korean glyphys, so it's less immersive when I type in Canvas in Korean. 
**So I hope you guys support font for Korean.**

There is a font called Nanum Pen Script that I feel is somewhat similar. 
Do you have any plans to apply these as sub-fonts?

Thank you for reading. 
Have a good day :)

### Contact Details

contactharry97@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment] 2024-07-23 15:21
dupe of https://github.com/tldraw/tldraw/issues/1263

**Closed by mimecuvalo** 2024-07-23 15:21 UTC
