### ISSUE TITLE
[Bug]: paste large image has wrong size

### ISSUE THREAD

**Issue by kaala** [tldraw/tldraw#3136] opened 2024-03-13 01:49 UTC
### What happened?

When I copy/paste screen capture into canvas, If the image is large, the image size is smaller than the actual size.
The image size should always be the actual size, so screen capture has consist scale.
![image](https://github.com/tldraw/tldraw/assets/246542/488bd5b7-aa31-4fc5-b8e6-8f4aefecc1b1)

### How can we reproduce the bug?

1. click print screen key and select a small portion of the screen
2. paste to tldraw
3. click print screen key and select the entire screen
4. paste to tldraw
5. you will see image1 and image2 has different scale
expect the scale is consist between image1 and image2

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomeHats** [comment] 2024-03-13 11:40
I'm going to close this for now as this is working as intended, but if the workaround doesn't work for you feel free to reopen!

**Closed** 2024-03-13 11:41 UTC
Labels: bug, wontfix

**Comment by kaala** [comment] 2024-03-16 03:25
I understand, but zoom out before paste is very inconvenient.
Could you make a keyboard shortcut or a right click menu to resize the image back to the original size?
