### ISSUE TITLE
[bug] HTMLContainer doesn't trigger hover and select events

### ISSUE THREAD

**Issue by parties** [tldraw/tldraw#601] opened 2022-03-01 03:03 UTC
First I just want to say: fantastic work on this project, thank you for making it open source! 🙌 

### Description

I've created an HTMLContainer component (`Node`), and it appears that the hover event isn't triggering for `onPointerEnter` (selection also seems bugged, could be related).

#### Reproduction
CodeSandbox: https://codesandbox.io/s/fancy-shadow-rsjx2r

Use the triangle alert icon to draw a new Node object (behaves similarly to regular `Box` shape): ![image](https://user-images.githubusercontent.com/6612736/156096058-503c2512-1967-499d-bccf-6f4bb7a2184a.png)

![image](https://user-images.githubusercontent.com/6612736/156096174-f9bc7bb4-8f8f-4a4f-aa33-6f876309da28.png)

- Notice that the event `HOVERED_SHAPE` doesn't trigger when you mouse in and out of the `Node` (debugger in bottom right)
- selection is also bugged, and only happens when you click and drag a box around the shape, but it does update the React component inside with the correct `isSelected` value

Thanks for the help! 😄

**Comment by steveruizok** [comment] 2022-03-09 12:33
Closing this, it's the intended behavior! 

See my reply here: https://github.com/tldraw/tldraw/pull/603#issuecomment-1062713040 

Short story: you need to "opt in" to pointer events by setting `pointer-events` on a shape's elements.

**Closed by steveruizok** 2022-03-09 12:33 UTC
Labels: bug
