### ISSUE TITLE
[Feature]: Hope the connecting line supports elbows

### ISSUE THREAD

**Issue by wisinfun** [tldraw/tldraw#3077] opened 2024-03-06 05:38 UTC
### What's the feature?

Hope the connecting line supports elbows, Very useful in creating flowcharts
<img width="1029" alt="image" src="https://github.com/tldraw/tldraw/assets/41355260/cef1ec50-8dd3-444b-8190-7e3ae5212413">

### Contact Details

wisinfun@qq.com

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment] 2024-07-22 14:26
dupe of https://github.com/tldraw/tldraw/issues/1738

**Closed by mimecuvalo** 2024-07-22 14:26 UTC
Labels: enhancement
