### ISSUE TITLE
Encountered this error while trying to ungroup a text element and a rectangle element: b0S >= b0S

### ISSUE THREAD

**Issue by rushabh-ss** [tldraw/tldraw#4210] opened 2024-07-18 06:31 UTC
Hey, I ran into an error while using tldraw. I was trying to ungroup a rectangle element and text element using the keyboard shortcut `CTRL`+`SHIFT`+`G`:

```js
Error: b0S >= b0S
    at Ml (https://www.tldraw.com/assets/index-DKx_6mVa.js:105:5033)
    at qi (https://www.tldraw.com/assets/index-DKx_6mVa.js:105:5769)
    at Hc (https://www.tldraw.com/assets/index-DKx_6mVa.js:105:5876)
    at re.reparentShapes (https://www.tldraw.com/assets/index-DKx_6mVa.js:138:61672)
    at https://www.tldraw.com/assets/index-DKx_6mVa.js:138:82958
    at https://www.tldraw.com/assets/index-DKx_6mVa.js:134:38408
    at tq (https://www.tldraw.com/assets/index-DKx_6mVa.js:105:17740)
    at zi (https://www.tldraw.com/assets/index-DKx_6mVa.js:105:17919)
    at ete.batch (https://www.tldraw.com/assets/index-DKx_6mVa.js:134:38400)
    at re.batch (https://www.tldraw.com/assets/index-DKx_6mVa.js:138:27361)
    at re.ungroupShapes (https://www.tldraw.com/assets/index-DKx_6mVa.js:138:82808)
    at Object.onSelect (https://www.tldraw.com/assets/index-DKx_6mVa.js:329:7864)
    at Object.method (https://www.tldraw.com/assets/index-DKx_6mVa.js:357:50665)
    at Sk (https://www.tldraw.com/assets/index-DKx_6mVa.js:357:46663)
    at wk (https://www.tldraw.com/assets/index-DKx_6mVa.js:357:47979)
    at HTMLBodyElement.p (https://www.tldraw.com/assets/index-DKx_6mVa.js:357:48785)
    at HTMLBodyElement.r (https://www.tldraw.com/assets/index-DKx_6mVa.js:89:1426)
```

My browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

https://github.com/user-attachments/assets/bb982d41-8bea-426e-964c-4b1cbf7f6224

**Comment by MitjaBezensek** [comment] 2024-07-23 08:33
Hey! Is there any chance you could send us this document? You can save it by going to File -> Save a copy.

**Comment by rushabh-ss** [comment] 2024-07-24 07:23
I have modified it since opening this issue. I'll attempt to reproduce the problem and send the document if successful, though I think this is unlikely given the changes made.

**Comment by mimecuvalo** [comment] 2024-07-24 12:42
duplicate of https://github.com/tldraw/tldraw/issues/3932

**Closed by mimecuvalo** 2024-07-24 12:42 UTC
