### ISSUE TITLE
Palm hits still firing before pen

### ISSUE THREAD

**Issue by SomeHats** [tldraw/tldraw#2048] opened 2023-10-10 10:36 UTC
1. Using the pen
2. Rest palm against screen
3. Draw with the pen

expected: The initial palm marks will be erased
actual: they remain

**Comment by Taha-Hassan-Git** [comment] 2024-04-22 08:39
Originally reported here: https://github.com/tldraw/tldraw/issues/1436

**Comment by mimecuvalo** [comment] 2024-07-22 13:51
dupe of https://github.com/tldraw/tldraw/issues/1436, as mentioned above

**Closed by mimecuvalo** 2024-07-22 13:51 UTC
