### ISSUE TITLE
viewport/page URL updating helper in library

### ISSUE THREAD

**Issue by SomeHats** [tldraw/tldraw#4168] opened 2024-07-15 10:15 UTC

**Comment by mimecuvalo** [comment] 2024-07-24 12:40
i think a dupe of https://github.com/tldraw/tldraw/issues/4157 but lemme know if otherwise @SomeHats

**Closed by mimecuvalo** 2024-07-24 12:40 UTC

**Comment by SomeHats** [comment] 2024-07-24 13:35
this is separate (adding a helper for SDK users vs having this functionality in the examples app) but happy to close for now
