### ISSUE TITLE
[Bug]: If the parent element is scaled, all tool positions will be abnormal. 

### ISSUE THREAD

**Issue by StringKe** [tldraw/tldraw#4139] opened 2024-07-11 08:30 UTC
### What happened?

When the scale of the parent element is not 1, all tools will be offset and their positions will be incorrect.

### How can we reproduce the bug?

Toggle zoom and use the brush at different zooms

https://codesandbox.io/p/sandbox/tldraw-example-forked-785nmd

### What browsers are you seeing the problem on?

Chrome

### Contact Details

stringke@126.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment] 2024-07-22 09:56
Closing this, looks like a duplicate of https://github.com/tldraw/tldraw/issues/1865

**Closed by MitjaBezensek** 2024-07-22 09:56 UTC
Labels: bug
