### ISSUE TITLE
No feedback when uploading an image

### ISSUE THREAD

**Issue by ds300** [tldraw/tldraw#2164] opened 2023-11-07 12:14 UTC
When you add an image, there's a delay where nothing happens

**Comment by irg1008** [comment] 2023-12-13 15:00
Could be related with #2320
Since the asset import process is wrongly downscaling the image, and therefore the bigger size slows the shape from spawning in the editor.

It has nothing to do with the feedback but would speed up the import considerably I think

**Comment by MitjaBezensek** [comment] 2024-07-22 14:03
Duplicate of https://github.com/tldraw/tldraw/issues/1567

**Closed by MitjaBezensek** 2024-07-22 14:03 UTC
